
export const SUPABASE_URL = 'https://xfrnxqxaxxuqqutohdwe.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnc3lrd21paWZlaXNmanhodGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzAxNzMsImV4cCI6MjA2NTcwNjE3M30.Mhbsgh1qwM0xpHdCMgMFeOVJ0DWd9dHU1ve2s10yBSQ';
