
export const SUPABASE_URL = 'https://xfrnxqxaxxuqqutohdwe.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmcm54cXhheHh1cXF1dG9oZHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjM1NjUsImV4cCI6MjA2MzgzOTU2NX0.lvOyPYtCxR6ESVf8th0fam4CdwGCp0GEmibpbbpSAs0';
