// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfrnxqxaxxuqqutohdwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmcm54cXhheHh1cXF1dG9oZHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjM1NjUsImV4cCI6MjA2MzgzOTU2NX0.lvOyPYtCxR6ESVf8th0fam4CdwGCp0GEmibpbbpSAs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});